version: '3.7'
services:
  snake_server:
    container_name: snake-server
    build:
      context: .
      dockerfile: ./env.d/docker.d/Dockerfile
      target: server
    user: "root:root"
    ports: ["8081:8080"]
    depends_on:
      snake_db:
        condition: service_healthy
      snake_map_editor:
        condition: service_started
  snake_map_editor:
    container_name: snake-map-editor
    build:
      context: .
      dockerfile: ./env.d/docker.d/Dockerfile
      target: editor
    user: "root:root"

  snake_db:
    image: postgres:15-alpine
    container_name: snake-db
    env_file: docker.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports: ["5433:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  snake_redis:
    image: "redis:alpine"
    container_name: snake-redis

volumes:
  postgres_data:
