// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: proto/editor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Obstacle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cx int32 `protobuf:"varint,1,opt,name=cx,proto3" json:"cx,omitempty"` // up-left cell X coordinate
	Cy int32 `protobuf:"varint,2,opt,name=cy,proto3" json:"cy,omitempty"` // up-left cell Y coordinate
}

func (x *Obstacle) Reset() {
	*x = Obstacle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Obstacle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obstacle) ProtoMessage() {}

func (x *Obstacle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obstacle.ProtoReflect.Descriptor instead.
func (*Obstacle) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{0}
}

func (x *Obstacle) GetCx() int32 {
	if x != nil {
		return x.Cx
	}
	return 0
}

func (x *Obstacle) GetCy() int32 {
	if x != nil {
		return x.Cy
	}
	return 0
}

type MapStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width     int32       `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height    int32       `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Obstacles []*Obstacle `protobuf:"bytes,3,rep,name=obstacles,proto3" json:"obstacles,omitempty"`
}

func (x *MapStruct) Reset() {
	*x = MapStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapStruct) ProtoMessage() {}

func (x *MapStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapStruct.ProtoReflect.Descriptor instead.
func (*MapStruct) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{1}
}

func (x *MapStruct) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapStruct) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapStruct) GetObstacles() []*Obstacle {
	if x != nil {
		return x.Obstacles
	}
	return nil
}

type Map struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Struct *MapStruct `protobuf:"bytes,2,opt,name=struct,proto3" json:"struct,omitempty"`
}

func (x *Map) Reset() {
	*x = Map{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{2}
}

func (x *Map) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Map) GetStruct() *MapStruct {
	if x != nil {
		return x.Struct
	}
	return nil
}

type CheckMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Struct *MapStruct `protobuf:"bytes,1,opt,name=struct,proto3" json:"struct,omitempty"`
}

func (x *CheckMapRequest) Reset() {
	*x = CheckMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMapRequest) ProtoMessage() {}

func (x *CheckMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMapRequest.ProtoReflect.Descriptor instead.
func (*CheckMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{3}
}

func (x *CheckMapRequest) GetStruct() *MapStruct {
	if x != nil {
		return x.Struct
	}
	return nil
}

type CheckMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckMapResponse) Reset() {
	*x = CheckMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMapResponse) ProtoMessage() {}

func (x *CheckMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMapResponse.ProtoReflect.Descriptor instead.
func (*CheckMapResponse) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{4}
}

type SaveMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Struct *MapStruct `protobuf:"bytes,1,opt,name=struct,proto3" json:"struct,omitempty"`
}

func (x *SaveMapRequest) Reset() {
	*x = SaveMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMapRequest) ProtoMessage() {}

func (x *SaveMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMapRequest.ProtoReflect.Descriptor instead.
func (*SaveMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{5}
}

func (x *SaveMapRequest) GetStruct() *MapStruct {
	if x != nil {
		return x.Struct
	}
	return nil
}

type SaveMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map *Map `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
}

func (x *SaveMapResponse) Reset() {
	*x = SaveMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMapResponse) ProtoMessage() {}

func (x *SaveMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMapResponse.ProtoReflect.Descriptor instead.
func (*SaveMapResponse) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{6}
}

func (x *SaveMapResponse) GetMap() *Map {
	if x != nil {
		return x.Map
	}
	return nil
}

type GetMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMapRequest) Reset() {
	*x = GetMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapRequest) ProtoMessage() {}

func (x *GetMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapRequest.ProtoReflect.Descriptor instead.
func (*GetMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{7}
}

func (x *GetMapRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map *Map `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
}

func (x *GetMapResponse) Reset() {
	*x = GetMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse) ProtoMessage() {}

func (x *GetMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse.ProtoReflect.Descriptor instead.
func (*GetMapResponse) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{8}
}

func (x *GetMapResponse) GetMap() *Map {
	if x != nil {
		return x.Map
	}
	return nil
}

var File_proto_editor_proto protoreflect.FileDescriptor

var file_proto_editor_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x08,
	0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x63, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x63, 0x79, 0x22, 0x69, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x52, 0x09, 0x6f, 0x62, 0x73, 0x74, 0x61, 0x63,
	0x6c, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x03, 0x4d, 0x61, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x22, 0x3c, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x0e, 0x53, 0x61, 0x76, 0x65, 0x4d,
	0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x64, 0x69, 0x74,
	0x6f, 0x72, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x22, 0x30, 0x0a, 0x0f, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x61,
	0x70, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x03, 0x6d, 0x61, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x4d, 0x61, 0x70, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x32, 0xbc, 0x01, 0x0a, 0x06, 0x45, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x12, 0x3d, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x12,
	0x17, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x16, 0x2e,
	0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x12, 0x15, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x65, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_editor_proto_rawDescOnce sync.Once
	file_proto_editor_proto_rawDescData = file_proto_editor_proto_rawDesc
)

func file_proto_editor_proto_rawDescGZIP() []byte {
	file_proto_editor_proto_rawDescOnce.Do(func() {
		file_proto_editor_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_editor_proto_rawDescData)
	})
	return file_proto_editor_proto_rawDescData
}

var file_proto_editor_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_editor_proto_goTypes = []any{
	(*Obstacle)(nil),         // 0: editor.Obstacle
	(*MapStruct)(nil),        // 1: editor.MapStruct
	(*Map)(nil),              // 2: editor.Map
	(*CheckMapRequest)(nil),  // 3: editor.CheckMapRequest
	(*CheckMapResponse)(nil), // 4: editor.CheckMapResponse
	(*SaveMapRequest)(nil),   // 5: editor.SaveMapRequest
	(*SaveMapResponse)(nil),  // 6: editor.SaveMapResponse
	(*GetMapRequest)(nil),    // 7: editor.GetMapRequest
	(*GetMapResponse)(nil),   // 8: editor.GetMapResponse
}
var file_proto_editor_proto_depIdxs = []int32{
	0, // 0: editor.MapStruct.obstacles:type_name -> editor.Obstacle
	1, // 1: editor.Map.struct:type_name -> editor.MapStruct
	1, // 2: editor.CheckMapRequest.struct:type_name -> editor.MapStruct
	1, // 3: editor.SaveMapRequest.struct:type_name -> editor.MapStruct
	2, // 4: editor.SaveMapResponse.map:type_name -> editor.Map
	2, // 5: editor.GetMapResponse.map:type_name -> editor.Map
	3, // 6: editor.Editor.CheckMap:input_type -> editor.CheckMapRequest
	5, // 7: editor.Editor.SaveMap:input_type -> editor.SaveMapRequest
	7, // 8: editor.Editor.GetMap:input_type -> editor.GetMapRequest
	4, // 9: editor.Editor.CheckMap:output_type -> editor.CheckMapResponse
	6, // 10: editor.Editor.SaveMap:output_type -> editor.SaveMapResponse
	8, // 11: editor.Editor.GetMap:output_type -> editor.GetMapResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_editor_proto_init() }
func file_proto_editor_proto_init() {
	if File_proto_editor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_editor_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Obstacle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MapStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Map); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CheckMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CheckMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SaveMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SaveMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_editor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_editor_proto_goTypes,
		DependencyIndexes: file_proto_editor_proto_depIdxs,
		MessageInfos:      file_proto_editor_proto_msgTypes,
	}.Build()
	File_proto_editor_proto = out.File
	file_proto_editor_proto_rawDesc = nil
	file_proto_editor_proto_goTypes = nil
	file_proto_editor_proto_depIdxs = nil
}
