// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/editor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Editor_CheckMap_FullMethodName = "/editor.Editor/CheckMap"
	Editor_SaveMap_FullMethodName  = "/editor.Editor/SaveMap"
	Editor_GetMap_FullMethodName   = "/editor.Editor/GetMap"
)

// EditorClient is the client API for Editor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EditorClient interface {
	CheckMap(ctx context.Context, in *CheckMapRequest, opts ...grpc.CallOption) (*CheckMapResponse, error)
	SaveMap(ctx context.Context, in *SaveMapRequest, opts ...grpc.CallOption) (*SaveMapResponse, error)
	GetMap(ctx context.Context, in *GetMapRequest, opts ...grpc.CallOption) (*GetMapResponse, error)
}

type editorClient struct {
	cc grpc.ClientConnInterface
}

func NewEditorClient(cc grpc.ClientConnInterface) EditorClient {
	return &editorClient{cc}
}

func (c *editorClient) CheckMap(ctx context.Context, in *CheckMapRequest, opts ...grpc.CallOption) (*CheckMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMapResponse)
	err := c.cc.Invoke(ctx, Editor_CheckMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) SaveMap(ctx context.Context, in *SaveMapRequest, opts ...grpc.CallOption) (*SaveMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMapResponse)
	err := c.cc.Invoke(ctx, Editor_SaveMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) GetMap(ctx context.Context, in *GetMapRequest, opts ...grpc.CallOption) (*GetMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMapResponse)
	err := c.cc.Invoke(ctx, Editor_GetMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EditorServer is the server API for Editor service.
// All implementations must embed UnimplementedEditorServer
// for forward compatibility.
type EditorServer interface {
	CheckMap(context.Context, *CheckMapRequest) (*CheckMapResponse, error)
	SaveMap(context.Context, *SaveMapRequest) (*SaveMapResponse, error)
	GetMap(context.Context, *GetMapRequest) (*GetMapResponse, error)
	mustEmbedUnimplementedEditorServer()
}

// UnimplementedEditorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEditorServer struct{}

func (UnimplementedEditorServer) CheckMap(context.Context, *CheckMapRequest) (*CheckMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckMap not implemented")
}
func (UnimplementedEditorServer) SaveMap(context.Context, *SaveMapRequest) (*SaveMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMap not implemented")
}
func (UnimplementedEditorServer) GetMap(context.Context, *GetMapRequest) (*GetMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMap not implemented")
}
func (UnimplementedEditorServer) mustEmbedUnimplementedEditorServer() {}
func (UnimplementedEditorServer) testEmbeddedByValue()                {}

// UnsafeEditorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EditorServer will
// result in compilation errors.
type UnsafeEditorServer interface {
	mustEmbedUnimplementedEditorServer()
}

func RegisterEditorServer(s grpc.ServiceRegistrar, srv EditorServer) {
	// If the following call pancis, it indicates UnimplementedEditorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Editor_ServiceDesc, srv)
}

func _Editor_CheckMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).CheckMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Editor_CheckMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).CheckMap(ctx, req.(*CheckMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_SaveMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).SaveMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Editor_SaveMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).SaveMap(ctx, req.(*SaveMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_GetMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).GetMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Editor_GetMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).GetMap(ctx, req.(*GetMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Editor_ServiceDesc is the grpc.ServiceDesc for Editor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Editor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "editor.Editor",
	HandlerType: (*EditorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckMap",
			Handler:    _Editor_CheckMap_Handler,
		},
		{
			MethodName: "SaveMap",
			Handler:    _Editor_SaveMap_Handler,
		},
		{
			MethodName: "GetMap",
			Handler:    _Editor_GetMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/editor.proto",
}
